# -*- coding: utf-8 -*-
{
    'name': "Solvera OJT Management",
    'summary': "Integrated On The Job Training (OJT) program management.",
    'description': """
        This module provides a comprehensive system for managing OJT programs, 
        from recruitment to e-certificate generation.
    """,
    'author': "Solvera Indonesia (Developed with AI Assistant)",
    'website': "https://www.solvera.id",
    'category': 'Human Resources/Recruitment',
    'version': '18.0.1.0.0',
    'depends': [
        'base',
        'hr_recruitment',
        'event',
        'website_slides',
        'survey',
        'portal',
        'website',
        'mail',
        'board',
    ],
    'data': [
        'security/ojt_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        # 'data/cron.xml',
        'data/mail_templates.xml',
        'views/ojt_event_link_views.xml',
        'views/event_event_views.xml',
        'views/ojt_batch_views.xml',
        'views/ojt_participant_views.xml',
        'views/ojt_attendance_views.xml',
        'views/ojt_assignment_views.xml',
        'views/ojt_submission_views.xml',
        'views/ojt_certificate_views.xml',
        'views/hr_applicant_views.xml',
        'views/ojt_reporting_views.xml',
        'views/menu.xml',
        'wizard/hr_applicant_enroll_views.xml',
        'wizard/generate_certificates_wizard_views.xml',
        'report/report_actions.xml',
        'report/certificate_templates.xml',
        'views/portal_templates.xml',
        'views/website_templates.xml',
    ],
    'installable': True,
    'application': True,
    "auto_install": True,
    'license': 'LGPL-3'
}